[2024-08-26 07:37:38,029][basic_search][INFO][color_logger.py:203] Logfile: /gyc_data/fray_data/project_hw/logs_gray_clapboard_search/basic_search_2024-08-26-07-37-38-029292.log
[2024-08-26 07:37:38,054][basic_search][INFO][generic_advisor.py:231] [BO auto selection]  acq_type: ei. acq_optimizer_type: random_scipy.
[2024-08-26 07:37:38,055][basic_search][WARNING][base.py:64] [Build Surrogate] Use probabilistic random forest based on scikit-learn. For better performance, please install pyrfr: https://open-box.readthedocs.io/en/latest/installation/install_pyrfr.html
[2024-08-26 07:37:38,057][basic_search][INFO][html_visualizer.py:462] Please open the html file to view visualization result: file:///gyc_data/fray_data/project_hw/logs_gray_clapboard_search/history/basic_search/basic_search_2024-08-26-07-37-38-055561.html
[2024-08-26 07:37:38,067][basic_search][ERROR][generic_smbo.py:290] Exception in objective function:
Traceback (most recent call last):
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/gyc_data/fray_data/project_hw/bayes.py", line 85, in obj_func
    cost = self.black_box.get_cost_from_seq(seq)
  File "/gyc_data/fray_data/project_hw/bayes.py", line 47, in get_cost_from_seq
    print(output_param.sequence.item() ,total_cost)
AttributeError: 'LP_c_uint' object has no attribute 'item'

config: Configuration(values={
  'x0': 0.125,
  'x1': 0.5,
  'x2': 0.2,
  'x3': 0.1428571429,
  'x4': 1.0,
  'x5': 0.25,
  'x6': 0.1111111111,
  'x7': 0.3333333333,
  'x8': 0.1,
  'x9': 0.1666666667,
})

[2024-08-26 07:37:38,067][basic_search][INFO][generic_smbo.py:310] Iter 1, objectives: [inf].
[2024-08-26 07:37:38,067][basic_search][INFO][html_visualizer.py:96] Please open the html file to view visualization result: file:///gyc_data/fray_data/project_hw/logs_gray_clapboard_search/history/basic_search/basic_search_2024-08-26-07-37-38-055561.html
[2024-08-26 07:37:38,070][basic_search][WARNING][history.py:559] No feasible incumbent observations returned!
